exports.config = {
    devHost: "127.0.0.1",
    devPort: "8899",
    devPath: "http://127.0.0.1:8899",
    proPath: "/dist/js",
    cssDistPath: "./dist/css",
    cssSrcPath: "./src/less",
    cssDistFileName: "dist/css",
    cssSrcFileName: "src/less",
    imgDistPath: "./dist/img",
    imgSrcPath: "./src/img",
    imgDistFileName: "dist/img",
    imgSrcFileName: "src/img",
    jsDistPath: "./dist/js",
    jsSrcPath: "./src/js",
    jsDistFileName: "dist/js",
    jsSrcFileName: "src/js",
    htmlDistPath: "./views",
    htmlSrcPath: "./src/html",
    htmlDistFileName: "views",
    htmlSrcFileName: "src/html",
    fileTypeReg: /(.*)\.((js)|(css))$/,
    buildJsFileReg: /(\/dist\/)(.*)\/(.*)\.(js)/g,
    buildCssFileReg: /(\/dist\/)(.*)\/(.*)\.(css)/g
} 